### ISSUE TITLE
Use sh/fileutil to remove duplicate code

### ISSUE THREAD

**Issue by mvdan** [dreadl0ck/zeus#3]
I noticed that you were copying some code from my non-importable `shfmt` package, so I made it readily available in a new package: https://github.com/mvdan/sh/commit/7ab538ac1885ee1ad391bd099a6f1e95d00639aa

**Comment by dreadl0ck** [comment]
@mvdan Great, thanks!

I've added a check in the formatPath() function, file formatter.go, line 148, to prevent writing an empty result into the file: "if !bytes.Equal(src, res) && len(res) > 0 {"

That happened to me one time when I was working on a script, I hit save a few times and the whole script was suddenly gone, apparently overwritten with an empty buffer.

Since I've added the additional check that did not happen again.

**Comment by mvdan** [comment]
@dreadl0ck I don't know how that would happen, unless you forgot to check for an error or use a buffered writer somewhere and forgot to flush.

If you can reproduce it, please file a bug.

**Comment by dreadl0ck** [comment]
@mvdan This has nothing to do with your library dont worry!

I think this happended because multiple write events were fired in ZEUS, the first one triggered a formatting of the file, the file was truncated for rewriting and then the next write event came in, leading to the currently empty file contents of the truncated file being formatted and written to the file.

I'll refactor the formatter to block any further format events on a file that is currently being formatted.

**Comment by dreadl0ck** [comment]
I did some cleanup and now use the new sh/fileutil package! Thanks!

**Comment by mvdan** [comment]
Preparing for 1.2.0, I've come up with better names for the stuff in `fileutil`: https://github.com/mvdan/sh/commit/99686b65adc5586b2d380dadce92932dea30cb33

Sorry to break your build, but this wouldn't happen if you were vendoring fileutil :)

**Comment by dreadl0ck** [comment]
Haha no problem I'll add fileutil to the vendored packages soon. Thanks for the Info!
